# Site settings
title: Cindy Colorado
email: cindy@cindycolorado.com
phone: 9704939333
description: "I am excited to design and sew your dreams and ideas into tangible concepts, working models, prototypes and production–ready products."
baseurl: ""
url: "http://cindycolorado.com"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [output,content]

navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Hats
    url: /hats/
  - text: Bucket Buddies
    url: /bucketbuddies/
  - text: Contact
    url: /contact/

