baseURL = "https://cindycolorado.com/"
languageCode = "en-us"
title = "Cindy Colorado"

theme = "initio"

[params]
  name = "Cindy Colorado"
  # description = "I am excited to design and sew your dreams and ideas into tangible concepts, working models, prototypes and production–ready products."
  description = "Welcome to Cindy Colorado LLC, where we design, prototype and sew all kinds of handmade goods."
  email = "cindy@cindycolorado.com"
  phone =  "(970) 493 9333"
  address = "846 Greenfields Court, Fort Collins, CO 80524"
  year = 2018
  background = "/img/fabric_army.jpg"
  favicon = "/img/favicon.png"
  DateForm = "January 2, 2006"

  showSubheader = true
  showServices = false
  showRecentWorks = false
  showDownload = false
  showClients = false

  footerEnableContact = true
  footerEnableFollowme = true
  footerEnableTextWidget = false
  footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[params.social]]
  title = "email"
  url = "mailto:cindy@cindycolorado.com"
    icon = "fa-envelope"
    footer = true
    sharethis = false
    network = "email"

[markup.goldmark.renderer]
unsafe= true

